update

diff --git a/codemagic.yaml b/codemagic.yaml
--- a/codemagic.yaml
+++ b/codemagic.yaml
@@ -1,7 +1,82 @@
+android-workflow:
+    name: Android workflow
+    # environment:
+      # groups:
+        # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
+        # - keystore_credentials # <-- (Includes KEYSTORE, KEYSTORE_PASSWORD, KEY_ALIAS_PASSWORD, KEY_ALIAS, KEYSTORE_PATH)
+          # KEYSTORE <-- Put your keystore file here
+          # KEYSTORE_PASSWORD <-- Put your keystore password here
+          # KEY_ALIAS_PASSWORD <-- Put your keystore alias password here
+          # KEY_ALIAS <-- Put your keystore alias username here
+          # KEYSTORE_PATH: '/tmp/keystore.keystore'
+        # - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS - Put your google-services.json here)
+    #     - other
+    #   xcode: 12.4
+    #   node: 12
+    #   npm: 6       
+    triggering:
+      events:
+        - push
+        - tag
+        - pull_request
+      branch_patterns:
+        - pattern: master
+          include: true
+          source: true 
+    # cache:
+    #   cache_paths:
+    #     - $FCI_BUILD_DIR/node_modules
+    scripts:
+      - name: Install dependencies
+        script: |
+          npm install
+          npm ci
+          cvm install 9.0.0
+          cvm use 9.0.0
+          npm install -g ionic
+          ionic info        
+          echo "Hello Android Dev greate work"
+      # - name: Add Android platform
+      #   script: |
+      #     set -x
+      #     ionic cordova platform remove android --nosave
+      #     ionic cordova platform add android --confirm --no-interactive --noresources
+      # - name: Build Android
+      #   script: |    
+      #     set -x
+      #     set -e
+      #     ionic cordova build android --release --no-interactive --prod --device
+      #     echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
+      #     UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
+      #     jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore "${KEYSTORE_PATH}" -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_ALIAS_PASSWORD}" "${UNSIGNED_APK_PATH}" "${KEY_ALIAS}"
+      #     mv $UNSIGNED_APK_PATH $(echo $UNSIGNED_APK_PATH | sed 's/-unsigned//')
+    # artifacts:
+    #   - platforms/android/app/build/outputs/**/*.apk
+    #   - platforms/android/app/build/outputs/**/mapping.txt
+    # publishing:
+    #     # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
+    #     email:
+    #         recipients:
+    #             - user_1@example.com
+    #             - user_2@example.com
+    #         notify:
+    #           success: true     # To not receive a notification when a build succeeds
+    #           failure: false    # To not receive a notification when a build fails
+    #     slack: 
+    #       # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
+    #       channel: '#channel-name'
+    #       notify_on_build_start: true   # To receive a notification when a build starts
+    #       notify:
+    #         success: true               # To not receive a notification when a build succeeds
+    #         failure: false              # To not receive a notification when a build fails
+    #     google_play:
+    #       # See the following link for information regarding publishing to Google Play - https://docs.codemagic.io/publishing-yaml/distribution/#google-play
+    #       credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
+    #       track: alpha    
 workflows:
   ios-workflow:
     name: iOS workflow
-    # environment:
+    environment:
       # groups:
         # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
           #- app_store_credentials # <-- (Includes APP_STORE_CONNECT_ISSUER_ID, APP_STORE_CONNECT_KEY_IDENTIFIER, APP_STORE_CONNECT_PRIVATE_KEY)
@@ -12,11 +87,13 @@ workflows:
             # https://appstoreconnect.apple.com/access/api
           #- certificate_credentials # <-- (Includes CERTIFICATE_PRIVATE_KEY - Put your Certificate Private Key here)
           #- other
-      # vars:      
-      #   BUNDLE_ID: "io.ionic.starter" # <-- Put your Bundle Id here 
-      # xcode: 12.4
-      # node: 12
-      # npm: 6
+      vars:      
+        XCODE_WORKSPACE: "MyApp.xcworkspace" # <-- Put the name of your Xcode workspace here
+        XCODE_SCHEME: "MyApp" # <-- Put the name of your Xcode scheme here        
+        BUNDLE_ID: "io.ionic.starter" # <-- Put your Bundle Id here 
+      node: latest
+      xcode: latest
+      cocoapods: default
     triggering:
       events:
         - push
@@ -102,79 +179,4 @@ workflows:
     #      submit_to_testflight: false                     # Optional boolean, defaults to false. Whether or not to submit the uploaded build to TestFlight beta review. Required for distributing to beta groups. Note: This action is performed during post-processing.
     #      #  beta_groups:                                 # Specify the names of beta tester groups that will get access to the build once it has passed beta review. 
     #      #     - group name 1
-    #      #     - group name 2     
-  android-workflow:
-    name: Android workflow
-    # environment:
-      # groups:
-        # Add the group environment variables in Codemagic UI (either in Application/Team variables) - https://docs.codemagic.io/variables/environment-variable-groups/
-        # - keystore_credentials # <-- (Includes KEYSTORE, KEYSTORE_PASSWORD, KEY_ALIAS_PASSWORD, KEY_ALIAS, KEYSTORE_PATH)
-          # KEYSTORE <-- Put your keystore file here
-          # KEYSTORE_PASSWORD <-- Put your keystore password here
-          # KEY_ALIAS_PASSWORD <-- Put your keystore alias password here
-          # KEY_ALIAS <-- Put your keystore alias username here
-          # KEYSTORE_PATH: '/tmp/keystore.keystore'
-        # - google_play # <-- (Includes GCLOUD_SERVICE_ACCOUNT_CREDENTIALS - Put your google-services.json here)
-    #     - other
-    #   xcode: 12.4
-    #   node: 12
-    #   npm: 6       
-    triggering:
-      events:
-        - push
-        - tag
-        - pull_request
-      branch_patterns:
-        - pattern: master
-          include: true
-          source: true 
-    # cache:
-    #   cache_paths:
-    #     - $FCI_BUILD_DIR/node_modules
-    scripts:
-      - name: Install dependencies
-        script: |
-          npm install
-          npm ci
-          cvm install 9.0.0
-          cvm use 9.0.0
-          npm install -g ionic
-          ionic info        
-          echo "Hello Android Dev greate work"
-      # - name: Add Android platform
-      #   script: |
-      #     set -x
-      #     ionic cordova platform remove android --nosave
-      #     ionic cordova platform add android --confirm --no-interactive --noresources
-      # - name: Build Android
-      #   script: |    
-      #     set -x
-      #     set -e
-      #     ionic cordova build android --release --no-interactive --prod --device
-      #     echo $KEYSTORE | base64 --decode > $KEYSTORE_PATH
-      #     UNSIGNED_APK_PATH=$(find platforms/android/app/build/outputs -name "*.apk" | head -1)
-      #     jarsigner -sigalg SHA1withRSA -digestalg SHA1 -keystore "${KEYSTORE_PATH}" -storepass "${KEYSTORE_PASSWORD}" -keypass "${KEY_ALIAS_PASSWORD}" "${UNSIGNED_APK_PATH}" "${KEY_ALIAS}"
-      #     mv $UNSIGNED_APK_PATH $(echo $UNSIGNED_APK_PATH | sed 's/-unsigned//')
-    # artifacts:
-    #   - platforms/android/app/build/outputs/**/*.apk
-    #   - platforms/android/app/build/outputs/**/mapping.txt
-    # publishing:
-    #     # See the following link for details about email publishing - https://docs.codemagic.io/publishing-yaml/distribution/#email
-    #     email:
-    #         recipients:
-    #             - user_1@example.com
-    #             - user_2@example.com
-    #         notify:
-    #           success: true     # To not receive a notification when a build succeeds
-    #           failure: false    # To not receive a notification when a build fails
-    #     slack: 
-    #       # See the following link about how to connect your Slack account - https://docs.codemagic.io/publishing-yaml/distribution/#slack
-    #       channel: '#channel-name'
-    #       notify_on_build_start: true   # To receive a notification when a build starts
-    #       notify:
-    #         success: true               # To not receive a notification when a build succeeds
-    #         failure: false              # To not receive a notification when a build fails
-    #     google_play:
-    #       # See the following link for information regarding publishing to Google Play - https://docs.codemagic.io/publishing-yaml/distribution/#google-play
-    #       credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
-    #       track: alpha      
+    #      #     - group name 2       
